apiVersion: batch/v1
kind: Job
metadata:
  name: prpsl-app-job
spec:
  template:
    spec:
      containers:
      - name: prpsl-app-job
        image: yash5090/prpsl-app:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
