apiVersion: apps/v1
kind: Deployment
metadata:
  name: prpsl-app-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: prpsl-app
  template:
    metadata:
      labels:
        app: prpsl-app
    spec:
      containers:
        - name: prpsl-app
          image: yash5090/prpsl-app:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
